replicaCount: 1

image:
  repository: mzupan/hello
  tag: 0.1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  paths: []
  hosts:
    - helloworld.local

env:
  - name: VERSION
    value: "0.1.0"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
